### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/datacube#1]
Origin: https://github.com/radiantearth/stac-spec/issues/713

> Two things came up recently that could be integrated into the data cube extension:
> 
> 1. Add variables in addition to dimensions. Some data cubes expose variables, some don't. We don't need this for openEO (yet?), but Google Earth Engine @simonff would probably use them. I'm also looking at netCDF and other formats, which afaik support variables as addition to dimensions. Maybe there's space for alignment also with the ESM collection spec "fork" from @rabernat.
> 2. For dimensions it might be useful to specify the number of cells (see openEO UDF discussions).

**Comment by schwehr** [comment]
@m-mohr Please dedup https://github.com/stac-extensions/datacube/issues/1#issue-822435277

**Comment by m-mohr** [comment]
Done
