### ISSUE TITLE
Information about values

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/datacube#13]
Allow a way to provide information about the data cube values, right now this extension is focused on dimensions, variables and labels.
Should probably be aligned with raster:bands. (We can't use raster:bands as not all datacubes may have bands.)

Potential fields:
- Data type
- Statistics
- ...

**Comment by m-mohr** [comment]
so probably to be aligned with the STAC classification extension

**Comment by matthewhanson** [comment]
Discussed in STAC sprint.

This will be resolved in STAC 1.1 as there will be a common metadata Statistics object. 

See https://github.com/radiantearth/stac-spec/pull/1254
