### ISSUE TITLE
Update data cube extension based on scientific schema

### ISSUE THREAD

**Issue by jbants** [stac-extensions/datacube#4]
The json schema has changed based on the scientific schema and we need to check if this extension json schema needs to change as well.

related pr:
https://github.com/stac-extensions/scientific/pull/2

**Comment by m-mohr** [comment]
The "not" > "additionalProperties" > "not" (i.e. "contains") schema structure is coming from here: https://github.com/json-schema-org/json-schema-spec/issues/1077
