### ISSUE TITLE
Additional fields in variables and/or dimensions

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/datacube#8]
> I had a discussion with @gilbertocamara on the topic. In the Brazil Data Cube we work with three dimensions + the `eo:bands`. We used this [document](https://github.com/radiantearth/stac-spec/blob/v0.9.0/extensions/datacube/examples/example-item.json) as a basis,  at the time we created the STAC service. 
>
> What do you think about including the datatype, missing-data, scale and chunking schema to the [variable](https://github.com/stac-extensions/datacube/blob/c4f4819fe037586067c80c7b9ab7339f6e35dfaf/README.md#variable-object) definition?

_Originally posted by @gqueiroz in https://github.com/stac-extensions/datacube/issues/6#issuecomment-846186095_

Related issue: #7

**Comment by m-mohr** [comment]
I think we should re-use the other extensions as far as possible. We could generally say that some (e.g. proj, raster/file) or all extensions can be re-used in variables and/or dimensions. Problem could be that in raster the fields are defined per band and thus we planned to remove them from file.

**Comment by TomAugspurger** [comment]
Here's an example:

```
{
  "cube:variables": {
    "prcp": {
      "type": "data",
      "description": "...",
      "extent": [0, null],
      "unit": "mm",
      "dimensions": ["time", "y", "x"],
      // new chunking information below //
      "shape": [365, 1000, 1000],
      "chunks": [1, 100, 100]
    }
}
```

Another problem with `proj:shape` is that it has to be length-2: https://github.com/stac-extensions/projection/blob/7f1d1c9db7c33dba0944972a983d74fd480d4c62/json-schema/schema.json#L163-L171. We would need the shape to be the same length as `dimensions` (e.g. `time, y, x, height, ensemble_id)`

**Comment by TomAugspurger** [comment]
> I think we should re-use the other extensions as far as possible. We could generally say that some (e.g. proj, raster/file) or all extensions can be re-used in variables and/or dimensions.

Do you know how this would be expressed in JSON schema (an example or a link to docs)? I've been trying to figure out how to "compose" JSON Schema  definitions (e.g. to add the requirement that `unit` is [CF-compliant](https://cfconventions.org/Data/cf-standard-names/77/build/cf-standard-name-table.html), or to add additional fields like `standard_name` or `attrs`).

**Comment by matthewhanson** [comment]
Discussed in STAC Sprint.

This is mostly solved by Bands RFC: https://github.com/radiantearth/stac-spec/pull/1254
to be implemented in next version of STAC.

It does not handle the chunking metadata, which seems more appropriate in the files extension or somewhere else.   If still needed please open up discussion in stac-spec repo.
